# Site settings
title: H1NT.me
email: root@h1nt.me
permalink: /:categories/:title
description: >
  Все подсказки для программистов!
baseurl: ""
url: "http://h1nt.me"
twitter_user: "H1NTme"

# Build settings
markdown: kramdown

sass:
    style: :compressed
defaults:
  -
    scope:
      path: _posts/ru
    values:
      layout: hints
      lang: ru
      category: "ru"
  -
    scope:
      path: _posts/en
    values:
      layout: hints
      lang: en
      category: "en"
t:
  link: "/"
  ru:
    lang:    "ru"
    slogan:  "Все подсказки, шпаргалки, клавиатурные сокращения в одном месте. Просто найти и просто использовать. <br> Это то, что вам нужно!"
    short:  "Мы коллекционируем шпаргалки и подсказки"
    search:  "Поиск"
    all:     "Все"
    about:   "О проекте"
  en:
    lang:    "en"
    slogan:  "All hints, cheaysheets, keyboard shortcuts brought together in one place. Easy to find and use. <br> Exactly what you need! ;)"
    short:  "We are Collecting all Cheatsheets in one Place!"
    search:  "Search"
    all:     "All"
    about:   "About"